version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: inventory
    restart: always
    environment:
      POSTGRES_USER: juan
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: student
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
